modLoader = "javafml" #mandatory
loaderVersion="${neo_loader_version_range}" #mandatory
license = "AGPLv3"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "haybalelib" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Tenzin's Lib" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile = "icon.png" #optional
credits = "Hero" #optional
authors = "t2pellet" #optional
description = '''
A ported library mod for Tenzin's mods!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]]
    modId = "neoforge" #mandatory
    mandatory = true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.2]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "cloth_config"
    mandatory = false
    versionRange = "${cloth_range}"
    ordering="BEFORE"
    side="BOTH"