plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.41'
}
base {
    archivesName = "${mod_name}-neoforge-${minecraft_version}"
}

jarJar.enable()
//neogradle.subsystems.devLogin.enabled=fals/e
//if (file('src/main/resources/META-INF/accesstransformer.cfg') != null) {
//
//    userDev {
//        accessTransformers {
//            // Automatically enable forge AccessTransformers if the file exists

//        }
//    }
//}
        if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
            accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
        }
runs {
    configureEach {
        modSource project.sourceSets.main
    }
    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }
    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}


sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    compileOnly project(":Common")
    implementation ("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_version}")
    implementation 'org.ini4j:ini4j:0.5.4'
    jarJar('org.ini4j:ini4j version: [0.5.0,0.6.0)') {
        jarJar.pin(it, '0.5.4')
    }
}

Spec<Task> notNeo = { Task tmp -> !tmp.name.startsWith("neo") } as Spec<Task>

tasks.withType(JavaCompile).matching(notNeo).configureEach {
    source(project(":Common").sourceSets.main.allSource)
}
tasks.withType(Javadoc).matching(notNeo).configureEach {
    source(project(":Common").sourceSets.main.allJava)
}
tasks.named("sourcesJar", Jar) {
    from(project(":Common").sourceSets.main.allSource)
}

tasks.withType(ProcessResources).matching(notNeo).configureEach {
    from project(":Common").sourceSets.main.resources
}

jar {
    archiveClassifier = 'slim'
    finalizedBy 'reobfJar'
}

tasks.named('jarJar') {
    archiveClassifier = ''
}

//publishing {
//    publications {
//        mavenJava(MavenPublication) {
//            artifactId base.archivesName.get()
//            from components.java
//            fg.component(it)
//        }
//    }
//    repositories {
//        maven {
//            url "file://" + System.getenv("local_maven")
//        }
//    }
//}
